CALL code --install-extension CoenraadS.bracket-pair-colorizer-2
CALL code --install-extension eg2.vscode-npm-script
CALL code --install-extension EQuimper.react-native-react-redux
CALL code --install-extension esbenp.prettier-vscode
CALL code --install-extension ms-python.python
CALL code --install-extension ms-vscode-remote.remote-containers
CALL code --install-extension ms-vscode-remote.remote-wsl
CALL code --install-extension ms-vscode.cpptools
CALL code --install-extension mushan.vscode-paste-image
CALL code --install-extension PKief.material-icon-theme
CALL code --install-extension puorc.awesome-vhdl
CALL code --install-extension sdras.night-owl
CALL code --install-extension vscodevim.vim